### ISSUE TITLE
Crashes if too many publishes occur

### ISSUE THREAD

**Issue by adamvr** [adamvr/mqtt-growl#1]
node-growl spawns a new growlnotify process for each notification and if we get a whole heap of publishes it tends to hit the process limit. 

```
child_process.js:477
    throw errnoException(errno, 'spawn');
    ^
Error: spawn EMFILE
    at errnoException (child_process.js:514:11)
    at ChildProcess.spawn (child_process.js:477:11)
    at child_process.js:375:9
    at Object.execFile (child_process.js:285:15)
    at child_process.js:252:18
    at growl (/usr/local/lib/node_modules/mqtt-growl/node_modules/growl/lib/growl.js:187:3)
    at Connection.<anonymous> (/usr/local/lib/node_modules/mqtt-growl/mqtt-growl:64:9)
    at Connection.emit (events.js:67:17)
    at Connection.parse (/usr/local/lib/node_modules/mqtt-growl/node_modules/mqttjs/lib/connection.js:108:9)
    at Socket.emit (events.js:67:17)
```

Consider migrating to something that has a persistent connection to the growl server or throttle node-growl somehow.

Suggestions:

https://github.com/betamos/Node-Growler

**Comment by adamvr** [comment]
Stopgap solution implemented with -d parameter. Still not really good enough.
